name: Deploy to gh-pages branch
on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install htmlc globally
        run: npm install -g @sojs_coder/htmlc
        
      - name: Build Sitemap
        run: node generate_sitemap.js
        
      - name: Build static site
        run: htmlc static --out=build
        
      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          publish_branch: gh-pages  # Explicitly set the target branch
          force_orphan: true        # Create a new history for gh-pages branch, keeping it clean
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'Deploy: ${{ github.event.head_commit.message }}'
          enable_jekyll: false      # Since this is a static site, disable Jekyll processing
